version: '3'

services:
  nginx:
    build:
       context: .
       dockerfile: Dockerfile-nginx
    image: wms/nginx
    container_name: nginx
    depends_on: 
      - app
    ports:
      - "80:443"
      - "443:443"
    networks:
      - private
    restart: always
#   volumes:
#      - ./nginx/conf:/etc/nginx/conf.d
#      - ./nginx/cert:/etc/nginx
  
  mysql:
    build:
       context: .
       dockerfile: Dockerfile-data
    image: wms/data
    container_name: mysql
    volumes:
      - ./DATA:/var/lib/mysql
#      - ./wms.sql:/docker-entrypoint-initdb.d/wms.sql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wms
      MYSQL_USER: stefan
      MYSQL_PASSWORD: passwd
    networks:
      - private

  app:
    image: wms/app:latest
    container_name: app
    depends_on: 
      - mysql
    restart: always
#    environment:
#       APP_DB_HOST: mysql
#       APP_DB_USER: stefan
#       APP_DB_PASSWORD: passwd
    volumes:
      - ./LOG:/var/log
    networks:
      - private

networks:
    private:
      driver: bridge
